In [1]:
import numpy as np

# 创建两个一维数组
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 垂直堆叠
result = np.vstack((a, b))

print(result)

[[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np

# 创建两个二维数组
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# 垂直堆叠
result = np.vstack((a, b))

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 垂直堆叠
v_result = np.vstack((a, b))
print("垂直堆叠:\n", v_result)

# 水平堆叠
h_result = np.hstack((a, b))
print("水平堆叠:\n", h_result)

垂直堆叠:
 [[1 2 3]
 [4 5 6]]
水平堆叠:
 [1 2 3 4 5 6]
